### ISSUE TITLE
运行的时候视频没有动

### ISSUE THREAD

**Issue by zhuliqian** [xjg0124/Video_Smoke_Detection#10]
只加入视频可以播放，加入模型后显示到第八帧然后停止不动，出现小窗口motion_detection,是为什么啊

**Comment by weilanShi** [comment]
> 只加入视频可以播放，加入模型后显示到第八帧然后停止不动，出现小窗口motion_detection,是为什么啊

你已经跑通了吗？可以加个QQ或微信不，QQ：1304020120

**Comment by zhuliqian** [comment]
@weilanShi     当时只是测试了下看效果，没有训练。

**Comment by weilanShi** [comment]
> 只加入视频可以播放，加入模型后显示到第八帧然后停止不动，出现小窗口motion_detection,是为什么啊
我在测试时也是这样显示，卡在第7帧不动，请问你解决了吗

**Comment by sirthisman** [comment]
我也出现了这个问题……报错如下
2019-09-03 16:01:51.200414: E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7600 (compatibility version 7600) but source was compiled with 7102 (compatibility version 7100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
2019-09-03 16:01:51.201006: F tensorflow/core/kernels/conv_ops_3d.cc:399] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)

**Comment by sirthisman** [comment]
> 我也出现了这个问题……报错如下
> 2019-09-03 16:01:51.200414: E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7600 (compatibility version 7600) but source was compiled with 7102 (compatibility version 7100). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
> 2019-09-03 16:01:51.201006: F tensorflow/core/kernels/conv_ops_3d.cc:399] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo(), &algorithms)

可能是显卡显存不够的问题，还是没解决

**Comment by sirthisman** [comment]
> > 我也出现了这个问题……报错如下
> > 2019-09-03 16:01:51.200414: E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7600 (compatibility version 7600) but source was compiled with 7102 (compatibility version 7100). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
> > 2019-09-03 16:01:51.201006: F tensorflow/core/kernels/conv_ops_3d.cc:399] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo(), &algorithms)
> 
> 可能是显卡显存不够的问题，还是没解决

解决了，用anaconda 创建的虚拟环境，python=3.6，tensorflow-gpu=1.10.0，可以跑通了
